name: notes_ai
description: A new Flutter project with AI chatbot and notes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1

  # State Management
  flutter_riverpod: ^2.4.9

  # UI
  flutter_markdown: ^0.6.18
  intl: ^0.19.0

  # AI Integration
  google_generative_ai: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  isar_generator: ^3.1.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true